Attempt to add by_vanilla_id protocol-specific accessor in World
Fails due to Rust's mutability rules:

error[E0502]: cannot borrow `*self` as immutable because it is also borrowed as mutable
   --> src/world/mod.rs:626:44
    |
600 |                 self.chunks.get_mut(&cpos).unwrap()
    |                 ----------- mutable borrow occurs here
...
626 |                     section.blocks.set(bi, self.by_vanilla_id(id as usize));
    |                                            ^^^^ immutable borrow occurs here
...
635 |                         ) + (chunk.position.0 << 4, (i << 4) as i32, chunk.position.1 << 4);
    |                              ---------------- mutable borrow later used here