Update to collision-rs git with num 0.2, without rustc-serialize
Using git version until in a release: https://github.com/rustgd/collision-rs/issues/106
Fixes wasm incompatibility in deprecated rustc-serialize crate:

error[E0046]: not all trait items implemented, missing: `encode`
    --> github.com-1ecc6299db9ec823/rustc-serialize-0.3.24/src/serialize.rs:1358:1